baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Henrys Sites'
theme = 'basic'
googleAnalytics = "UA-xxxxxxxxxxxx"

[params]
author = 'Henry'
description = 'A website' 
gh_url = "https://api.github.com/users"
gh_user = "henryhoorizadeh"


[caches]
  [caches.images]
    dir = ':cacheDir/images'