baseURL = 'https://henryhoorizadeh.github.io/'
languageCode = 'en-us'
title = 'Henrys Sites'
theme = 'basic'


[params]
author = 'Henry'
description = 'A website' 
gh_url = "https://api.github.com/users"
gh_user = "henryhoorizadeh"


[caches]
  [caches.images]
    dir = ':cacheDir/images'


[build]
  min_version = "0.147.2"